# mediamtx.yml
paths:
  all:
    authMethod: external
    authExternalAddress: http://drone_app:8080/auth
    authInternal: no
    record: no # Zarządzane przez app.py PATCH
    recordPath: /recordings/%path/%Y-%m-%d_%H-%M-%S
    recordFormat: mp4
    recordPartDuration: 10m
    recordDeleteAfter: 0s # Retencja zarządzana przez Python

rtsp: yes
rtmp: yes
api: yes
apiAddress: :9997
webrtc: yes
webrtcAddress: :8889
webrtcICEUDP: yes
webrtcServerHostname: stream.giswgorach.pl