# --- KONFIGURACJA DLA v1.15.6+ ---
# Nowy sposób autoryzacji zewnętrznej
authMethod: http
authHTTPAddress: http://drone_app:8080/auth

# Nowy sposób definiowania domyślnych parametrów zapisu
pathDefaults:
  recordPath: /recordings/%path/%Y-%m-%d_%H-%M-%S
  recordFormat: fmp4
  recordPartDuration: 10m

# WebRTC
webrtc: yes
webrtcAddress: :8889

paths:
  all:
    record: no