# --- KONFIGURACJA GLOBALNA ---
# Autoryzacja zewnętrzna (URL do Twojej aplikacji)
externalAuthenticationURL: http://drone_app:8080/auth

# Parametry zapisu (fmp4 jest nowocześniejszy i bezpieczniejszy)
recordFormat: fmp4
recordPath: /recordings/%path/%Y-%m-%d_%H-%M-%S
recordPartDuration: 10m

# WebRTC (Podgląd w przeglądarce)
webrtc: yes
webrtcAddress: :8889
webrtcServerHostname: stream.giswgorach.pl
# Parametr webrtcICEUDP został usunięty w nowych wersjach - MediaMTX sam zarządza portami.

# --- ŚCIEŻKI ---
paths:
  all:
    # Domyślnie wyłączamy autostart nagrywania (app.py będzie tym sterować)
    record: no